"""subscription portal token and ended_at

Revision ID: 0df5a45466e9
Revises: b6818791ef98
Create Date: 2026-06-23 10:22:52.481021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0df5a45466e9'
down_revision: Union[str, Sequence[str], None] = 'b6818791ef98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('subscriptions', sa.Column('portal_token', sa.String(), nullable=True))
    # Backfill a unique portal token for existing memberships.
    op.execute(
        "UPDATE subscriptions SET portal_token = 'mpt_' || replace(gen_random_uuid()::text, '-', '') "
        "WHERE portal_token IS NULL"
    )
    op.create_unique_constraint(None, 'subscriptions', ['portal_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscriptions', type_='unique')
    op.drop_column('subscriptions', 'portal_token')
    op.drop_column('subscriptions', 'ended_at')
    # ### end Alembic commands ###
