"""subscription line id

Revision ID: 3eb724a0e722
Revises: 4c6f7a5741ec
Create Date: 2026-06-23 12:32:24.786310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3eb724a0e722'
down_revision: Union[str, Sequence[str], None] = '4c6f7a5741ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('customer_line_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'customer_line_id')
    # ### end Alembic commands ###
