"""coupons notifications phone

Revision ID: 4c6f7a5741ec
Revises: 0df5a45466e9
Create Date: 2026-06-23 11:26:10.595816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c6f7a5741ec'
down_revision: Union[str, Sequence[str], None] = '0df5a45466e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('subscription_id', sa.String(), nullable=True),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('recipient', sa.String(), nullable=True),
    sa.Column('event', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_logs_created_at'), 'notification_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_notification_logs_merchant_id'), 'notification_logs', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_notification_logs_subscription_id'), 'notification_logs', ['subscription_id'], unique=False)
    op.create_table('coupons',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('discount_type', sa.String(), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('duration', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('max_redemptions', sa.Integer(), nullable=True),
    sa.Column('times_redeemed', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'code', name='uq_coupon_merchant_code')
    )
    op.create_index(op.f('ix_coupons_code'), 'coupons', ['code'], unique=False)
    op.create_index(op.f('ix_coupons_merchant_id'), 'coupons', ['merchant_id'], unique=False)
    op.add_column('subscriptions', sa.Column('customer_phone', sa.String(), nullable=True))
    op.add_column('subscriptions', sa.Column('coupon_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'subscriptions', 'coupons', ['coupon_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_column('subscriptions', 'coupon_id')
    op.drop_column('subscriptions', 'customer_phone')
    op.drop_index(op.f('ix_coupons_merchant_id'), table_name='coupons')
    op.drop_index(op.f('ix_coupons_code'), table_name='coupons')
    op.drop_table('coupons')
    op.drop_index(op.f('ix_notification_logs_subscription_id'), table_name='notification_logs')
    op.drop_index(op.f('ix_notification_logs_merchant_id'), table_name='notification_logs')
    op.drop_index(op.f('ix_notification_logs_created_at'), table_name='notification_logs')
    op.drop_table('notification_logs')
    # ### end Alembic commands ###
