"""refund void, receiving accounts, audit log

Revision ID: 71e9c2503272
Revises: 8749d3310026
Create Date: 2026-06-22 21:33:09.127488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71e9c2503272'
down_revision: Union[str, Sequence[str], None] = '8749d3310026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=True),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=True),
    sa.Column('target_id', sa.String(), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_merchant_id'), 'audit_logs', ['merchant_id'], unique=False)
    op.create_table('receiving_accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('promptpay_id', sa.String(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receiving_accounts_merchant_id'), 'receiving_accounts', ['merchant_id'], unique=False)
    op.add_column('charges', sa.Column('receiving_account_id', sa.String(), nullable=True))
    op.add_column('charges', sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('charges', sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('charges', sa.Column('refund_reason', sa.String(), nullable=True))
    op.create_foreign_key(None, 'charges', 'receiving_accounts', ['receiving_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'charges', type_='foreignkey')
    op.drop_column('charges', 'refund_reason')
    op.drop_column('charges', 'refunded_at')
    op.drop_column('charges', 'canceled_at')
    op.drop_column('charges', 'receiving_account_id')
    op.drop_index(op.f('ix_receiving_accounts_merchant_id'), table_name='receiving_accounts')
    op.drop_table('receiving_accounts')
    op.drop_index(op.f('ix_audit_logs_merchant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
