"""initial schema

Revision ID: 8749d3310026
Revises: 
Create Date: 2026-06-22 20:30:17.483907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8749d3310026'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('business_name', sa.String(), nullable=False),
    sa.Column('promptpay_id', sa.String(), nullable=True),
    sa.Column('webhook_url', sa.String(), nullable=True),
    sa.Column('webhook_secret', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchants_email'), 'merchants', ['email'], unique=True)
    op.create_table('api_keys',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('secret_hash', sa.String(), nullable=False),
    sa.Column('prefix', sa.String(), nullable=False),
    sa.Column('last_four', sa.String(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_merchant_id'), 'api_keys', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_api_keys_secret_hash'), 'api_keys', ['secret_hash'], unique=True)
    op.create_table('charges',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('promptpay_payload', sa.Text(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_charges_created_at'), 'charges', ['created_at'], unique=False)
    op.create_index(op.f('ix_charges_merchant_id'), 'charges', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_charges_status'), 'charges', ['status'], unique=False)
    op.create_table('webhook_deliveries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('charge_id', sa.String(), nullable=False),
    sa.Column('event', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_status_code', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_deliveries_charge_id'), 'webhook_deliveries', ['charge_id'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_merchant_id'), 'webhook_deliveries', ['merchant_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('charge_id', sa.String(), nullable=False),
    sa.Column('trans_ref', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sender_name', sa.String(), nullable=True),
    sa.Column('sender_bank', sa.String(), nullable=True),
    sa.Column('receiver_name', sa.String(), nullable=True),
    sa.Column('receiver_bank', sa.String(), nullable=True),
    sa.Column('transferred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['charge_id'], ['charges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_charge_id'), 'payments', ['charge_id'], unique=False)
    op.create_index(op.f('ix_payments_trans_ref'), 'payments', ['trans_ref'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_trans_ref'), table_name='payments')
    op.drop_index(op.f('ix_payments_charge_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_webhook_deliveries_merchant_id'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_charge_id'), table_name='webhook_deliveries')
    op.drop_table('webhook_deliveries')
    op.drop_index(op.f('ix_charges_status'), table_name='charges')
    op.drop_index(op.f('ix_charges_merchant_id'), table_name='charges')
    op.drop_index(op.f('ix_charges_created_at'), table_name='charges')
    op.drop_table('charges')
    op.drop_index(op.f('ix_api_keys_secret_hash'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_merchant_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_merchants_email'), table_name='merchants')
    op.drop_table('merchants')
    # ### end Alembic commands ###
