"""settlements and fees

Revision ID: 9293caf11b4b
Revises: 71e9c2503272
Create Date: 2026-06-22 22:31:41.621567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9293caf11b4b'
down_revision: Union[str, Sequence[str], None] = '71e9c2503272'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settlements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('fee_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('charge_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paid_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settlements_created_at'), 'settlements', ['created_at'], unique=False)
    op.create_index(op.f('ix_settlements_merchant_id'), 'settlements', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_settlements_status'), 'settlements', ['status'], unique=False)
    op.add_column('charges', sa.Column('settlement_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_charges_settlement_id'), 'charges', ['settlement_id'], unique=False)
    op.create_foreign_key(None, 'charges', 'settlements', ['settlement_id'], ['id'])
    # server_default so the NOT NULL backfills existing merchant rows.
    op.add_column('merchants', sa.Column('fee_percent', sa.Numeric(precision=5, scale=2), nullable=False, server_default='0'))
    op.add_column('merchants', sa.Column('fee_fixed', sa.Numeric(precision=8, scale=2), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merchants', 'fee_fixed')
    op.drop_column('merchants', 'fee_percent')
    op.drop_constraint(None, 'charges', type_='foreignkey')
    op.drop_index(op.f('ix_charges_settlement_id'), table_name='charges')
    op.drop_column('charges', 'settlement_id')
    op.drop_index(op.f('ix_settlements_status'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_merchant_id'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_created_at'), table_name='settlements')
    op.drop_table('settlements')
    # ### end Alembic commands ###
